name: Build executables

on: [push]

defaults:
  run:
    shell: bash

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Update Python version here

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller --onefile --name=app-${{ matrix.os }} raiplay-dl.py

      - name: Commit to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: New release of app-${{ matrix.os }}
